# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98ac01e6b611be1b372b33334d528f9948aed2a922730a16a94c3c96654f1f698f34165b318115f3873e91ec2279c0991e5c9adea786d0a8daa8cc0972193b00

test:
  secret_key_base: cb93107480e684e434ae5618a845a0e3b40f7a3ec6bf1bac795640f0180e7ac16e183a8e5da18ae7085142a8ade71ca12686ced6b13dab4147a35218de0915ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
